#GUESS THE NUMBER.
#two player game where they have to guess the number randomly generated by computer the one who will take less attempt to guess the number will win.
import random
def guess():
    a = random.choice(range)
    i=0
    while(True):
        i=i+1
        guess1=int(input(f"your guess number {i}"))
        if guess1==a:
            print(f"congratulation Your guess is correct\n you had taken {i} attempt to guess the number")
            return i
        elif guess1>a:
            print(f"your guess is wrong \n you should choose number smaller than this")
        elif guess1<a:
            print(f"your guess is wrong \n you should choose number bigger than this")

print("Welcome to the game of guess the number\n")
print("This game is two player game,The one who will take less attempt to guess the number wins the game\n")
name1=input("player 1 name")
name2=input("player 2 name")
print(f"welcome {name1} and {name2} to the game of guess the number\n")
print("Select the minimum and maximum range between which you will guess the numbers")
min=int(input("minimum"))
max=int(input("maximum"))
range=range(min,max)

print("Now lets start the game\n")
print(f" {name1} lets start with your guesses")
no1=guess()
print(f"Now its {name2} times to guess")
no2=guess()
if no1>no2:
    print(f"congratulation {name2} you are the winner")
elif no1==no2:
    print(f"This game is a draw between {name1} and {name2}")
elif no1<no2:
    print(f"congratulation {name1} you are the winner")




